package com.actito.geo.e2e.network.responses

import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class TestDeviceResponse(
    val device: Device,
) {
    @JsonClass(generateAdapter = true)
    data class Device(
        val location: Location,
        val deviceID: String,
        val userName: String,
        val autoGenerated: Boolean,
        val application: String,
        val medium: String,
        val deviceString: String,
        val language: String,
        val tags: List<String>,
        val active: Boolean,
        val expired: Boolean,
        val registrationDate: String,
        val timeZoneOffset: Int,
        val imported: Boolean,
        val inboxSize: Int,
        val inboxUnread: Int,
        val messageCount: Int,
        val allowedUI: Boolean,
        val lastActive: String,
        val platform: String,
        val transport: String,
        val osVersion: String,
        val sdkVersion: String,
        val appVersion: String,
        val osString: String,
        val origin: String?,
        val region: String?,
        val backgroundAppRefresh: Boolean,
        val userID: String,
    )

    @JsonClass(generateAdapter = true)
    data class Location(
        val type: String,
        val coordinates: List<Double>?,
    )
}
