complexity:
  TooManyFunctions:
    active: false
  LargeClass:
    active: false
  LongMethod:
    active: false
  CyclomaticComplexMethod:
    active: false
  LongParameterList:
    functionThreshold: 10

exceptions:
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false

naming:
  MatchingDeclarationName:
    active: false
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  PackageNaming:
    packagePattern: '[a-z]+(\.[a-z][a-z_]*)*'


style:
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: true
    excludeRawStrings: true
  ThrowsCount:
    active: false
  ReturnCount:
    active: false
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  UseCheckOrError:
    active: false
  UseRequire:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
